print('Helo world!')
print('Whats is your name?')
name = input()
print('It is good do meet you, ' + name)
print('The lenght of your name is: ' , len(name))
print('What is your age?')
age = input()
print('You will be ' + str(int(age) + 1) , 'in a year') 